// actions
export const FORM_PROJECT = "FORM_PROJECT";
export const REQUEST_PROJECTS = "REQUEST_PROJECTS";
export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";
export const FORM_VALIDATION = "FORM_VALIDATION";
export const ACTIVE_PROJECT = "ACTIVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
